export const POST_SELECTED_GLQ = "POST_SELECTED_GLQ";
export const POST_SELECTED_GLQ_FAILED = "POST_SELECTED_GLQ_FAILED";
export const POST_SELECTED_UNCL = "POST_SELECTED_UNCL";
export const POST_SELECTED_UNCL_FAILED = "POST_SELECTED_UNCL_FAILED";
export const POST_SELECTED_UNCX = "POST_SELECTED_UNCX";
export const POST_SELECTED_UNCX_FAILED = "POST_SELECTED_UNCX_FAILED";

